title: Resume/Portfolio Site
author: Sean Cleveland
email: 30681614+marlfoxlegend@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website to display my project portfolio
  and my resume for potential employers.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  marlfoxlegend # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
